"""add_llm_embedding_rerank_to_workspaces

Revision ID: b91b5650407c
Revises: 85270245ff06
Create Date: 2025-12-11 12:20:53.896787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b91b5650407c'
down_revision: Union[str, None] = '85270245ff06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy import inspect
    
    bind = op.get_bind()
    inspector = inspect(bind)
    columns = [col['name'] for col in inspector.get_columns('data_config')]
    
    if 'workspace_id' not in columns:
        op.add_column('data_config', sa.Column('workspace_id', sa.UUID(), nullable=True, comment='工作空间ID'))
    if 'llm_id' not in columns:
        op.add_column('data_config', sa.Column('llm_id', sa.String(), nullable=True, comment='LLM模型配置ID'))
    if 'embedding_id' not in columns:
        op.add_column('data_config', sa.Column('embedding_id', sa.String(), nullable=True, comment='嵌入模型配置ID'))
    if 'rerank_id' not in columns:
        op.add_column('data_config', sa.Column('rerank_id', sa.String(), nullable=True, comment='重排序模型配置ID'))
    if 'lambda_time' not in columns:
        op.add_column('data_config', sa.Column('lambda_time', sa.Float(), nullable=True, comment='最低保持度，0-1 小数'))
    if 'lambda_mem' not in columns:
        op.add_column('data_config', sa.Column('lambda_mem', sa.Float(), nullable=True, comment='遗忘率，0-1 小数'))
    if 'id' in columns:
        op.drop_column('data_config', 'id')
    if 'λ_mem' in columns:
        op.drop_column('data_config', 'λ_mem')
    if 'λ_time' in columns:
        op.drop_column('data_config', 'λ_time')
    op.alter_column('knowledges', 'permission_id',
               existing_type=sa.VARCHAR(),
               comment='permission ID:Private|Share|Memory',
               existing_comment='permission ID:Private|Share',
               existing_nullable=True)
    op.alter_column('memory_increments', 'created_at',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('memory_increments', 'updated_at',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    
    # Check workspaces columns
    workspace_columns = [col['name'] for col in inspector.get_columns('workspaces')]
    if 'llm' not in workspace_columns:
        op.add_column('workspaces', sa.Column('llm', sa.String(), nullable=True))
    if 'embedding' not in workspace_columns:
        op.add_column('workspaces', sa.Column('embedding', sa.String(), nullable=True))
    if 'rerank' not in workspace_columns:
        op.add_column('workspaces', sa.Column('rerank', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'rerank')
    op.drop_column('workspaces', 'embedding')
    op.drop_column('workspaces', 'llm')
    op.alter_column('memory_increments', 'updated_at',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('memory_increments', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('knowledges', 'permission_id',
               existing_type=sa.VARCHAR(),
               comment='permission ID:Private|Share',
               existing_comment='permission ID:Private|Share|Memory',
               existing_nullable=True)
    op.add_column('data_config', sa.Column('λ_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='最低保持度，0-1 小数'))
    op.add_column('data_config', sa.Column('λ_mem', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='遗忘率，0-1 小数'))
    op.add_column('data_config', sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=True, comment='模型配置 UUID'))
    op.drop_column('data_config', 'lambda_mem')
    op.drop_column('data_config', 'lambda_time')
    op.drop_column('data_config', 'rerank_id')
    op.drop_column('data_config', 'embedding_id')
    op.drop_column('data_config', 'llm_id')
    op.drop_column('data_config', 'workspace_id')
    # ### end Alembic commands ###
